spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: @gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  messages:
    basename: messages, errors
  datasource:
    url: jdbc:h2:tcp://localhost/~/hawaii
    username: sa
    password:
      driver-class-name: org.h2.Driver

#spring.io 공식사이트에 속성 설정 가이드가 있음
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    #org.apache.coyote.http11: debug





